### ISSUE TITLE
Crash At Connect

### ISSUE THREAD

**Issue by chakhedik** [essiene/smpp34#1]
Hi,

I tried to use your library but failed to connect with error below :

=CRASH REPORT==== 5-Apr-2011::14:29:16 ===
  crasher:
    initial call: smpp34_esme:init/1
    pid: <0.123.0>
    registered_name: []
    exception exit: {undef,
                        [{smpp34_esme_core_sup,start_child,
                             ["204.141.17.65",8000]},
                         {smpp34_esme,init,1},
                         {gen_fsm,init_it,6},
                         {proc_lib,init_p_do_apply,3}]}
      in function  gen_fsm:init_it/6
    ancestors: [<0.120.0>]
    messages: []
    links: []
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 377
    stack_size: 24
    reductions: 115
  neighbours:
{error,{undef,[{smpp34_esme_core_sup,start_child,
                                     ["204.141.17.65",8000]},
               {smpp34_esme,init,1},
               {gen_fsm,init_it,6},
               {proc_lib,init_p_do_apply,3}]}}

Please advise.

Chak

**Comment by essiene** [comment]
Could you please gimme the code snippet you called exactly? 

Hopefully you're on the master branch too right?

**Comment by chakhedik** [comment]
Hi,

I just ran your example from README (smpp34_example), nothing changed except for address and port. I've downloaded the version from download button above. Should I use git clone git://github.com/essiene/smpp34.git instead?I'll try....

Thanks for your reply.

Chak

**Comment by chakhedik** [comment]
Hi,

I've tried re-download using git clone but still got the same error.

Chak

**Comment by essiene** [comment]
Never mind. Found the problem. I've been using the gen_esme34 api more than the synchronous API, so didn't catch this bug when it crept in.

**Comment by essiene** [comment]
ok. I've fixed this by making the Logger optional for the Synchronous API.

Please pull master and try again.

The asynchronous API (gen_esme34) is advisable for anything more than a simple system. Examples for using that are availabe in examples/hello_esme.erl and examples/echo_esme.erl

Let me know your experience! ;)

**Comment by chakhedik** [comment]
Thanks, it work now...

I had to use the synchronous to fit my app...but I'll look into your asynchronous... 

Thanks again :)
