### ISSUE TITLE
Custom Sequence Number

### ISSUE THREAD

**Issue by chakhedik** [essiene/smpp34#3]
Hi,

How can I set my own sequence number before doing submit_sm?I can see it in main pdu record but don't know how to use it.

Thanks,
Ckah

**Comment by essiene** [comment]
Hiya,

On Tue, Apr 5, 2011 at 3:37 PM, chakhedik
reply@reply.github.com
wrote:

> Hi,
> 
> How can I set my own sequence number before doing submit_sm?I can see it in main pdu record but don't know how to use it.

When transmitting, gen_smpp34 will generate and send the Sequence
number for you.

When receiving and implementing handle_rx, you can specify the
Sequence Number as a response to handle_rx... I know... more
documentation ;). And example is in:
https://github.com/essiene/mmyn/blob/master/src/mmayen/esmerx.erl

See lines 45 to 58

**Comment by essiene** [comment]
On Tue, Apr 5, 2011 at 5:15 PM, Essien Essien essiene@gmail.com wrote:

> Hiya,
> 
> On Tue, Apr 5, 2011 at 3:37 PM, chakhedik
> reply@reply.github.com
> wrote:
> 
> > Hi,
> > 
> > How can I set my own sequence number before doing submit_sm?I can see it in main pdu record but don't know how to use it.
> 
> When transmitting, gen_smpp34 will generate and send the Sequence
> number for you.
> 
> When receiving and implementing handle_rx, you can specify the
> Sequence Number as a response to handle_rx... I know... more
> documentation ;). And example is in:
> https://github.com/essiene/mmyn/blob/master/src/mmayen/esmerx.erl
> 
> See lines 45 to 58

I've also just pushed some modifications to dev branch that allows you
to send the Serial Number directly.

See
- gen_esme34:transmit_pdu/5 (src/gen_esme34.erl)
- smpp34_esme:send/4 (src/smpp34_esme.erl)

I'll buckle up and add more documentation soon-ish ;)

**Comment by chakhedik** [comment]
Thank you so much, I really really appreciate that.

Yep more documentation would be more better :)

**Comment by essiene** [comment]
On Wed, Apr 6, 2011 at 2:11 AM, chakhedik
reply@reply.github.com
wrote:

> Thank you so much, I really really appreciate that.
> 
> Yep more documentation would be more better :)

I'll buckle down this weekend and put in some more user documentation.
I've focused so far on more architectural docs (or rather ramblings)
that would be usefull to someone contributing code to the framework.

User Docs are a' comin! :)
